### ISSUE TITLE
APA102 support is very inconsistent

### ISSUE THREAD

**Issue by solidcell** [intel-iot-devkit/upm#504]
The example [here](https://github.com/intel-iot-devkit/upm/blob/master/examples/java/APA102Sample.java) works fine as long as the brightness is high enough. `31` (the max) doesn't seem to pose any problems, but as soon as you get to `15` or lower, problems consistently arise.  Problems such as LEDs being off or being the wrong color.

I've tested this APA102 strip and the same power source with a Photon microcontroller and it works fine at very low brightness, so the only other variable is the Intel Edison hardware or software.

I've seen a lot of mentions that the Edison has poor support for SPI (it's emulated), so maybe it's related to that?

**Comment by Propanu** [comment]
Hi @solidcell, the SPI driver on the Edison has actually improved quite a bit with the new image, but there are still a few things you sometimes need to tweak based on device. For instance, PM used to cause problems if it's on when hooking up displays, you can read more about it [here](https://github.com/intel-iot-devkit/mraa/blob/master/docs/edison.md#intel-arduino-board). I don't recall if it's relevant for the LED strips but can be tried.

Then, make sure your SPI bus shares a common ground with the power supply. The issue you're describing is actually caused by the different characteristics of the SPI lines on the two boards. The number of LEDs on the strip also matters.

You have two options to fix that from the APA102 driver itself:
* The first one and likely to make the biggest impact is `batchMode`. Set it to `true` in the constructor call, draw your frame and then push it over the bus with a call to `pushState()` at the end.
* The second is to lower the SPI bus speed with the `setBusSpeed(int hz)` function. This will directly affect the length of the strip you can drive, and will likely need to be significantly lower when not using batch mode.

Let me know what works for you. Good luck!
